import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Button from '../UI/Button';
export default function Home() {
  const handleClick = () => {
    console.log('тык');
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Button onClick={handleClick} type='blue' iconPosition='left' icon='plus'>
        Это просто кнопка
      </Button>
    </div>
  );
}
