import {useEffect, useState} from 'react';
import Head from 'next/head';
import Block from '../UI/Block';
import Typography from '../UI/Typography';
import styles from '../styles/Home.module.css';
import axios from 'axios';

export default function Home() {
  useEffect(() => {
    // Simple use
    axios.get(`http://localhost:5000/sellers`).then(res => {
      const {sellers} = res.data;
      console.log(sellers);
    })

    axios.get(`http://localhost:5000/categories`).then(res => {
      const {sellers} = res.data;
      console.log(sellers);
    })

    axios.get(`http://localhost:5000/top`).then(res => {
      const {sellers} = res.data;
      console.log(sellers);
    })
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>NFT</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Block size='xl' background='main'>
          <Typography type='h2'>Top sellers</Typography>
        </Block>
    </div>
  );
}
