import Head from 'next/head';
import Block from '../UI/Block';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>NFT</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <Block size='xl' background='secondary'>
          1234
        </Block>
      </Head>
    </div>
  );
}
